server:
  port: 8081
  address: 127.0.0.1
spring:
  application:
    name: JMW.Tire
  profiles:
    active: dev

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
  #api-docs:
    #path: /v3/api-docs
#  group-configs:
#    - group: 'jmw'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  config: classpath:logback.xml
#  file:
#    path: log
#  pattern:
#    file: '%d %5p - %m%n'