spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?&allowMultiQueries=true&characterEncoding=utf-8
    username: mydb
    password: mydb

  security:
    user:
      name: jmw
      password: jmw

  web:
    resources:
      static-locations: classpath:/static/