#大傻逼
server:
  port: 8081
  address: 127.0.0.1
spring:
  application:
    name: JMW.Tire
  profiles:
    active: dev

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
  #api-docs:
    #path: /v3/api-docs
#  group-configs:
#    - group: 'jmw'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  config: classpath:logback.xml
#  file:
#    path: log
#  pattern:
#    file: '%d %5p - %m%n'

provider-entity:
  runnableThreadNum: 3
  name: 123
  source: 123
  data-sources:
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mydb
      password: waem8XcHS2BafkKz
      url: jdbc:mysql://152.136.154.249:3306/mydb?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code:
        - sql: "select * from user"
          str: username
      use-sql: true
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: demoT
      password: 6RHDcY4kJhjjnzHr
      url: jdbc:mysql://152.136.154.249:3306/demot?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code :
        - sql: "select * from Frend"
          str: username
      use-sql: true
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: demo
      password: kKJ8XynXLzjfYDA7
      url: jdbc:mysql://152.136.154.249:3306/demo?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code:
        - sql: "select * from user"
          str: username
      use-sql: true
